# Testing tools configuration
[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

# Formatting tools configuration
[tool.autopep8]
max-line-length = 99
ignore = ["W503"]
recursive = true
jobs = -1
aggressive = 3

[tool.isort]
profile = "black"

# Linting tools configuration
[tool.flake8]
max-line-length = 99
max-doc-length = 99
exclude = [".git", "__pycache__", ".tox", "build", "dist", "*.egg_info", "venv"]
select = ["E", "W", "F", "C", "N", "R", "D", "H"]
ignore = ["D105", "D107", "W503"]
# D100, D101, D102, D103, D104: Ignore missing docstrings in tests
per-file-ignores = ["test/*:D100,D101,D102,D103,D104"]
docstring-convention = "google"

[tool.pyright]
include = ["ops/*.py", "ops/_private/*.py",
    "test/test_private.py",
    "test/test_infra.py",
    "test/test_jujuversion.py",
    "test/test_log.py",
    "test/test_lib.py",
    "test/test_helpers.py",
]
pythonVersion = "3.8" # check no python > 3.8 features are used
pythonPlatform = "All"
typeCheckingMode = "strict"
reportIncompatibleMethodOverride = false
reportImportCycles = false
reportMissingModuleSource = false
reportPrivateUsage = false
reportUnnecessaryIsInstance = false
reportUnnecessaryComparison = false
stubPath = ""
