#!/usr/bin/env python3
"""Dry-run plan mode (PLAN.md Approach §4 delta).

Emits the exact, fully-resolved command sequence a runner branch would
execute for a hypothesis, *without executing anything* -- no juju, no
concierge, no charmcraft, no subprocess call anywhere in this module.
`seams/runner.py`'s `build_plan()` does the actual sequence construction
(shared with the real `SubprocessRunnerSeam` so a reviewed plan and a real
run can never silently diverge); this file is the CLI wrapper plus the
Markdown renderer used to produce a reviewable artefact.

Why this exists: there is no juju/k8s/charmcraft/cluster in this sandbox,
so the k8s-scratch/lxd-scratch orchestration in `seams/runner.py` is
unexercised code. A human is going to walk it by hand on a real multipass
VM -- reviewing a printed plan first costs seconds; discovering a wrong
command three rounds into a k8s bootstrap costs an hour (exactly the shape
of the three `render.py` bugs `spike-step-4/2639/RESULT.md` had to debug by
hand). Every plan this module produces is checked against
`runnability.assess()` before being written out, so an unfilled
`<placeholder>` argument (the trap `#2639`'s own hand extraction contains --
`juju deploy <k8s-charm-with-workload>`, which a shell reads as a redirect)
fails loudly here instead of surfacing three hours into a real walk.

Usage::

    uv run python dry_run.py --issue 2639
    uv run python dry_run.py --issue 2639 --out ../spike-step-5/2639-k8s-scratch-dry-run-plan.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import runnability
import runner_stage
from models import Hypothesis, SurfaceInference
from seams.runner import PlannedCommand, build_plan

HERE = Path(__file__).parent
DEFAULT_FIXTURES_DIR = HERE / "fixtures"


class PlanNotRunnable(RuntimeError):
    """Raised when a generated plan contains a command `runnability.assess()`
    would not survive contact with a shell -- the one thing a dry-run plan
    must never silently paper over."""


def load_hypothesis(issue_number: int, fixtures_dir: Path = DEFAULT_FIXTURES_DIR) -> Hypothesis:
    raw = json.loads((fixtures_dir / "extractions" / f"{issue_number}.json").read_text())
    return Hypothesis.from_dict(issue_number, raw)


def load_surface(issue_number: int, fixtures_dir: Path = DEFAULT_FIXTURES_DIR) -> SurfaceInference | None:
    path = fixtures_dir / "surface" / f"{issue_number}.json"
    if not path.exists():
        return None
    return SurfaceInference.from_dict(json.loads(path.read_text()))


def generate_plan(
    issue_number: int,
    *,
    fixtures_dir: Path = DEFAULT_FIXTURES_DIR,
    charm_dir: str | None = None,
    repo: str = "canonical/operator",
) -> tuple[str, list[PlannedCommand]]:
    """Returns `(branch, plan)`. Resolves the branch via the same
    `runner_stage.choose_branch()` the real pipeline uses, so the plan
    reflects the actual dispatch decision, not a hand-picked one.

    Raises `PlanNotRunnable` if any resolved command wouldn't survive
    contact with a shell -- checked with `runnability.assess()`, the same
    pre-run gate `runner_stage.check_runnable()` uses for the
    command-executing branches.
    """
    hypothesis = load_hypothesis(issue_number, fixtures_dir)
    surface = load_surface(issue_number, fixtures_dir)
    branch = runner_stage.choose_branch(hypothesis)
    context = {"repo": repo}
    if charm_dir:
        context["charm_dir"] = charm_dir
    elif branch in ("k8s-scratch", "lxd-scratch"):
        # A concrete, resolved path -- mirroring `pipeline.py`'s own
        # `work_dir / f"charm-{issue.number}"` convention -- not a
        # placeholder. Overridable via --charm-dir for a real dry run
        # pointed at an actual rendered-charm directory.
        context["charm_dir"] = f"work/charm-{issue_number}"

    plan = build_plan(branch=branch, hypothesis=hypothesis, surface=surface, context=context)

    report = runnability.assess([step.command for step in plan])
    if not report.runnable:
        raise PlanNotRunnable(f"#{issue_number} ({branch}): {report.reason}")

    return branch, plan


def render_markdown(issue_number: int, branch: str, plan: list[PlannedCommand]) -> str:
    lines = [
        f"# Dry-run plan — #{issue_number} ({branch})",
        "",
        "Generated by `harness/dry_run.py` (PLAN.md Approach §4 delta) -- not executed, not exercised "
        "against real juju/concierge/charmcraft. Every command below passed `runnability.assess()`: "
        "no prose, no unfilled `<placeholder>` arguments.",
        "",
    ]
    for i, step in enumerate(plan, start=1):
        lines.append(f"{i}. **{step.step}**")
        lines.append("")
        lines.append("   ```shell")
        lines.append(f"   {step.command}")
        lines.append("   ```")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--issue", type=int, required=True)
    parser.add_argument("--fixtures-dir", type=Path, default=DEFAULT_FIXTURES_DIR)
    parser.add_argument("--charm-dir", default=None, help="rendered charm directory to substitute (default: work/charm-<n>)")
    parser.add_argument("--repo", default="canonical/operator")
    parser.add_argument("--out", type=Path, default=None, help="write Markdown here instead of stdout")
    args = parser.parse_args()

    branch, plan = generate_plan(
        args.issue, fixtures_dir=args.fixtures_dir, charm_dir=args.charm_dir, repo=args.repo
    )
    markdown = render_markdown(args.issue, branch, plan)

    if args.out:
        args.out.write_text(markdown)
        print(f"wrote {len(plan)}-step {branch!r} plan for #{args.issue} to {args.out}")
    else:
        print(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
