#!/usr/bin/env python3
"""Render a scratch-charm skeleton from a params.yaml (moving_parts shape).

Usage: render.py params/<name>.yaml out/<name>/

Structural params (relation endpoint, storage stanza, pebble container) get
baked into charmcraft.yaml at render time -- juju needs these declared
statically, they can't be config options resolved at runtime. Behavioural
params (which handler to wire, the pebble service command) get baked into
src/charm.py as constants for the same reason: there is no "generic charm
that reads params.yaml at runtime and wires itself up" shape that would
still pack cleanly, and hardcoding keeps the generated charm inspectable.

params.yaml values ultimately trace back to LLM hypothesis-extraction
output (PLAN.md Approach §3) -- treat every string as untrusted. Structural
identifiers (relation/storage/container/service names) are validated
against juju's naming rules before being written into charmcraft.yaml or
Python source; free-form values (the pebble command) are never
string-interpolated -- they're embedded via json.dumps() so quotes/
newlines/backslashes can't break out of the generated source.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

import yaml

IDENT_RE = re.compile(r"^[a-z][a-z0-9-]*$")  # juju endpoint/storage/container names
SURFACES = {"update-status", "config-changed", "relation-changed", "pebble-custom-notice"}

# The status message the generated charm sets once it is up and observing,
# before anything has fired. Without it the charm sets no status at all
# until its surface fires, so there is no way to tell "ready and waiting"
# from "still installing" -- and the first real k8s run (2026-08-18)
# stimulated a unit that was still running its install hook, recording the
# notice before the observer existed. `juju wait-for ... active` is
# meaningful only because of this.
READY_STATUS = "reproducer ready"

# The literal status-message prefix each surface produces when it fires.
# This is the single source of truth for the classifier's
# `expected_signal`: the string is decided *here*, by the template, so
# asking an LLM to guess it can only ever introduce a mismatch (the first
# successful k8s stimulus, 2026-08-18, was scored against the invented
# "Received Pebble custom notice" while the charm emitted "observed
# notice: ...", so the signal could never be found whatever the bug did).
SURFACE_SIGNALS = {
    "update-status": "observed",
    "config-changed": "observed",
    "relation-changed": "observed relation data:",
    "pebble-custom-notice": "observed notice:",
}
ROLES = {"provider", "requirer"}
STORAGE_TYPES = {"filesystem", "block"}


class ParamError(ValueError):
    pass


def _check_ident(value, field):
    if value is not None and not IDENT_RE.match(value):
        raise ParamError(f"{field}={value!r} is not a valid juju identifier ([a-z][a-z0-9-]*)")


def load_params(path):
    with open(path) as f:
        params = yaml.safe_load(f) or {}

    relation = params.get("relation") or {}
    storage = params.get("storage") or {}
    pebble = params.get("pebble_service") or {}
    surface = params.get("ops_api_surface")

    _check_ident(relation.get("name"), "relation.name")
    _check_ident(relation.get("interface"), "relation.interface")
    if relation.get("role") not in (None, *ROLES):
        raise ParamError(f"relation.role must be one of {ROLES}, got {relation.get('role')!r}")

    _check_ident(storage.get("name"), "storage.name")
    if storage.get("type") not in (None, *STORAGE_TYPES):
        raise ParamError(f"storage.type must be one of {STORAGE_TYPES}")

    _check_ident(pebble.get("container"), "pebble_service.container")
    _check_ident(pebble.get("service"), "pebble_service.service")

    if surface not in (None, *SURFACES):
        raise ParamError(f"ops_api_surface must be one of {SURFACES}, got {surface!r}")

    if surface == "relation-changed" and not relation.get("name"):
        raise ParamError("ops_api_surface=relation-changed needs relation.name set")
    if surface == "pebble-custom-notice" and not pebble.get("container"):
        raise ParamError("ops_api_surface=pebble-custom-notice needs pebble_service.container set")

    return {
        "charm_name": params.get("charm_name", "reproducer-scratch"),
        "relation": relation,
        "storage": storage,
        "pebble_service": pebble,
        "ops_api_surface": surface,
        "source_issue": params.get("source_issue"),
    }


def build_charmcraft_yaml(p):
    doc = {
        "name": p["charm_name"],
        "title": "add-reproducer scratch charm",
        "summary": "Generated scaffolding for a single reproduction hypothesis.",
        "description": (
            "Generated by spike-step-3/charm/render.py from a hypothesis's "
            "moving_parts. Not hand-maintained -- re-render from params.yaml "
            "rather than editing charmcraft.yaml directly."
        ),
        "type": "charm",
    }
    if p["source_issue"]:
        doc["description"] += f" Source: operator#{p['source_issue']}."

    is_k8s = bool(p["pebble_service"].get("container"))
    if is_k8s:
        # Bare key form, matching the machine-charm branch's shape below.
        # No top-level `base`: the platform key already carries it, and
        # charmcraft rejects declaring both -- "Platform 'ubuntu@24.04:amd64'
        # declares a base and a top-level base or build-base is declared."
        # The 2026-07-22 fix for the original `platforms: {amd64: {}}` bug
        # switched to this key form but left the `base` line behind, which
        # made the pair mutually exclusive; charmcraft 4.3.1 enforces it and
        # nothing packed a rendered charm between then and the first real
        # run, so it went unnoticed.
        doc["platforms"] = {"ubuntu@24.04:amd64": None}
        container = p["pebble_service"]["container"]
        doc["containers"] = {container: {"resource": f"{container}-image"}}
        doc["resources"] = {
            f"{container}-image": {
                "type": "oci-image",
                "description": f"OCI image for the {container!r} container.",
            }
        }
    else:
        # Machine charm -- same platforms shape as charm-ubuntu.
        doc["platforms"] = {
            f"ubuntu@{v}:{a}": None
            for v in ("22.04", "24.04", "26.04")
            for a in ("amd64", "arm64")
        }

    if p["relation"].get("name"):
        role = p["relation"].get("role") or "requirer"
        key = "requires" if role == "requirer" else "provides"
        doc[key] = {
            p["relation"]["name"]: {"interface": p["relation"].get("interface") or "reproducer"}
        }

    if p["storage"].get("name"):
        entry = {
            "type": p["storage"].get("type") or "filesystem",
            "description": "Scratch storage for reproduction.",
            "minimum-size": "100M",
        }
        if entry["type"] == "filesystem":
            entry["location"] = p["storage"].get("location") or "/srv/data"
        doc["storage"] = {p["storage"]["name"]: entry}

    doc["parts"] = {"charm": {"plugin": "uv", "source": ".", "build-snaps": ["astral-uv"]}}
    return yaml.dump(doc, sort_keys=False, default_flow_style=False)


def build_charm_py(p):
    surface = p["ops_api_surface"]
    lines = [
        "#!/usr/bin/env python3",
        '"""Generated scratch charm -- do not hand-edit, re-run render.py."""',
        "",
        "import logging",
        "",
        "import ops",
        "",
        "logger = logging.getLogger(__name__)",
        "",
        "",
        "class ReproducerCharm(ops.CharmBase):",
        '    """Scaffolding charm wired for one reproduction hypothesis."""',
        "",
        "    def __init__(self, framework: ops.Framework):",
        "        super().__init__(framework)",
    ]

    lines.append("        framework.observe(self.on.start, self._ready)")

    observed = []
    if surface == "update-status":
        lines.append("        framework.observe(self.on.update_status, self._observe)")
        observed.append("update_status")
    elif surface == "config-changed":
        lines.append("        framework.observe(self.on.config_changed, self._observe)")
        observed.append("config_changed")
    elif surface == "relation-changed":
        rel = p["relation"]["name"].replace("-", "_")
        lines.append(f"        framework.observe(self.on.{rel}_relation_changed, self._observe)")
        observed.append(f"{rel}_relation_changed")
    elif surface == "pebble-custom-notice":
        container = p["pebble_service"]["container"].replace("-", "_")
        lines.append(
            f"        framework.observe("
            f"self.on.{container}_pebble_custom_notice, self._observe)"
        )
        observed.append(f"{container}_pebble_custom_notice")

    lines += [
        "",
        "    def _ready(self, event: ops.EventBase) -> None:",
        '        """Mark the unit up and observing.',
        "",
        "        Nothing else sets a status before the surface fires, so without",
        "        this a runner cannot tell a charm that is ready from one still",
        "        installing -- and stimulating too early records the event before",
        "        the observer is listening.",
        '        """',
        f"        self.unit.status = ops.ActiveStatus({json.dumps(READY_STATUS)})",
        "",
        "    def _observe(self, event: ops.EventBase) -> None:",
        '        """Surface whatever the reported bug is about, for inspection.',
        "",
        "        Sets unit status to a short summary of what fired so `juju status`",
        "        (or `ctx.run()`'s returned state, under ops.testing) is enough to",
        "        compare against the hypothesis's `observed` field -- no need to",
        "        shell into the unit for the common case.",
        '        """',
        f"        logger.info('reproducer surface fired: %s', {json.dumps(observed[0] if observed else None)})",
    ]

    if surface == "relation-changed":
        rel_name = p["relation"]["name"]
        lines += [
            f"        relation = self.model.get_relation({json.dumps(rel_name)})",
            "        data = dict(relation.data[self.app]) if relation else None",
            '        self.unit.status = ops.ActiveStatus(f"observed relation data: {data}")',
        ]
    elif surface == "pebble-custom-notice":
        container = p["pebble_service"]["container"]
        lines += [
            f"        container = self.unit.get_container({json.dumps(container)})",
            "        notice = getattr(event, 'notice', None)",
            "        key = getattr(notice, 'key', None)",
            "        self.unit.status = ops.ActiveStatus(f\"observed notice: {key} in {container.name}\")",
        ]
    else:
        lines += [
            '        self.unit.status = ops.ActiveStatus("observed")',
        ]

    lines += [
        "",
        "",
        "if __name__ == \"__main__\":",
        "    ops.main(ReproducerCharm)",
        "",
    ]
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        print("usage: render.py params/<name>.yaml out/<name>/", file=sys.stderr)
        raise SystemExit(2)

    params_path, out_dir = Path(sys.argv[1]), Path(sys.argv[2])
    p = load_params(params_path)

    (out_dir / "src").mkdir(parents=True, exist_ok=True)
    (out_dir / "charmcraft.yaml").write_text(build_charmcraft_yaml(p))
    (out_dir / "src" / "charm.py").write_text(build_charm_py(p))
    (out_dir / "pyproject.toml").write_text(
        '[project]\n'
        f'name = "{p["charm_name"]}"\n'
        'version = "0.0.0"\n'
        'requires-python = ">=3.10"\n'
        'dependencies = ["ops~=3.8"]\n'
        "\n"
        "[dependency-groups]\n"
        'unit = ["pytest", "ops[testing]~=3.8"]\n'
    )
    subprocess.run(["uv", "lock"], cwd=out_dir, check=True)
    print(f"rendered {out_dir}/ from {params_path}")


if __name__ == "__main__":
    main()
