name: Broad Charm Compatibility Tests

on:
  schedule:
    - cron: '0 1 25 * *'
  workflow_dispatch:

jobs:
  charm-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/data-platform-libs
          - charm-repo: canonical/kafka-operator
          - charm-repo: canonical/mongodb-operator
          - charm-repo: canonical/mysql-operator
          - charm-repo: canonical/traefik-k8s-operator
          - charm-repo: canonical/mysql-k8s-operator
          - charm-repo: canonical/mysql-router-k8s-operator
          - charm-repo: canonical/postgresql-operator
          - charm-repo: canonical/prometheus-k8s-operator
          - charm-repo: canonical/pgbouncer-k8s-operator
          - charm-repo: canonical/grafana-k8s-operator
          - charm-repo: canonical/postgresql-k8s-operator
          - charm-repo: canonical/discourse-k8s-operator
          - charm-repo: canonical/s3-integrator
          - charm-repo: canonical/zookeeper-operator
          - charm-repo: canonical/loki-k8s-operator
          - charm-repo: canonical/alertmanager-k8s-operator
          - charm-repo: canonical/openfga-operator
          - charm-repo: canonical/indico-operator
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/trino-k8s-operator
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/charm-layer-ghost
          - charm-repo: canonical/juju-charm-dokuwiki.rb
          - charm-repo: canonical/charm-openstack-service-checks
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/layer-arangodb
          - charm-repo: canonical/layer-ubuntu-devenv
          - charm-repo: canonical/charm-cilium
          - charm-repo: canonical/route53-lego-k8s-operator
          - charm-repo: canonical/wordpress-k8s-operator
          - charm-repo: canonical/temporal-k8s-operator
          - charm-repo: canonical/layer-filebeat
          - charm-repo: canonical/jenkins-agent-operator
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/layer-kapacitor
          - charm-repo: canonical/nfs-charm
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/layer-ssl-termination-fqdn
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/jenkins-charm
          - charm-repo: canonical/juju-dashboard
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/seldon-core-operator
          - charm-repo: canonical/layer-topbeat
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/nginx-ingress-integrator-operator
          - charm-repo: canonical/layer-openjdk
          - charm-repo: canonical/oathkeeper-operator
          - charm-repo: canonical/jenkins-agent-k8s-operator
          - charm-repo: canonical/grafana-agent-k8s-operator
          - charm-repo: canonical/metallb-operator
          - charm-repo: canonical/kubernetes
          - charm-repo: canonical/juju-dashboard
          - charm-repo: canonical/namecheap-lego-k8s-operator
          - charm-repo: canonical/superset-k8s-operator
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/identity-platform-login-ui-operator
          - charm-repo: canonical/temporal-admin-k8s-operator
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/dex-auth-operator
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/juju-layer-fresh-rss
          - charm-repo: canonical/ks-charmed
          - charm-repo: canonical/charm-lldpd
          - charm-repo: canonical/charm-kube-ovn
          - charm-repo: canonical/temporal-ui-k8s-operator
          - charm-repo: canonical/juju-charm-znc
          - charm-repo: canonical/notebook-operators
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/temporal-worker-k8s-operator
          - charm-repo: canonical/bigtop
          - charm-repo: canonical/charm-flannel
          - charm-repo: canonical/charm-prometheus-libvirt-exporter
          - charm-repo: canonical/content-cache-k8s-operator
          - charm-repo: canonical/ranger-k8s-operator
          - charm-repo: canonical/oauth2-proxy-k8s-operator
          - charm-repo: canonical/livepatch-k8s-operator
          - charm-repo: canonical/self-signed-certificates-operator
          - charm-repo: canonical/saml-integrator-operator
          - charm-repo: canonical/smtp-integrator-operator
          - charm-repo: canonical/manual-tls-certificates-operator
          - charm-repo: canonical/jimm
          - charm-repo: canonical/hardware-observer-operator
          - charm-repo: canonical/charmed-linstor
          - charm-repo: canonical/bundle
          - charm-repo: canonical/bundle
          - charm-repo: canonical/bundle-kubeflow
          - charm-repo: canonical/ecosystem-prep
          - charm-repo: canonical/bundle-jupyter
          - charm-repo: canonical/hello-juju-charm
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}

      - name: Checkout the operator repository
        uses: actions/checkout@v4
        with:
          path: myops

      - name: Install patch dependencies
        run: pip install poetry~=1.6

      - name: Update 'ops' dependency in test charm to latest
        run: |
          if [ -e "requirements.txt" ]; then
            sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
            echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt
          else
            sed -i -e "s/^ops[ ><=].*/ops = {path = \"myops\"}/" pyproject.toml
            poetry lock --no-update
          fi

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        run: tox -vve unit
